-- ============================================================
-- P21 Sales Order Pull — CSV Export Queries
-- EnPro Industries | 2026-04-03
-- Adjust the date filter as needed
-- ============================================================

-- ── SO HEADERS ─────────────────────────────────────────────
SELECT
    h.order_no,
    h.oe_hdr_uid,
    h.company_id,
    h.location_id,
    h.customer_id,
    h.address_id,
    h.corp_address_id,
    h.contact_id,
    h.bill_to_id,
    -- Ship-to
    h.ship2_name,
    h.ship2_add1,
    h.ship2_add2,
    h.ship2_add3,
    h.ship2_city,
    h.ship2_state,
    h.ship2_zip,
    h.ship2_country,
    h.ship2_email_address,
    h.ship2_url,
    h.ship_to_phone,
    -- Dates
    h.order_date,
    h.requested_date,
    h.requested_ship_date,
    h.promise_date,
    h.original_promise_date,
    h.expected_completion_date,
    h.expedite_date,
    h.date_order_completed,
    h.date_created,
    h.date_last_modified,
    h.acknowledgement_date,
    h.prebilling_date,
    -- PO / reference
    h.po_no,
    h.po_no_append,
    h.supplier_order_no,
    h.supplier_release_no,
    h.web_reference_no,
    h.invoice_no,
    -- Status
    h.order_type,
    h.completed,
    h.approved,
    h.cancel_flag,
    h.validation_status,
    h.supplier_status,
    h.inquiry_flag,
    h.projected_order,
    -- Shipping
    h.carrier_id,
    h.freight_code_uid,
    h.freight_out,
    h.fob_flag,
    h.packing_basis,
    h.delivery_instructions,
    h.pick_ticket_type,
    h.ship_confirmed_flag,
    h.will_call,
    h.front_counter,
    h.blind_ship_flag,
    h.ups_code,
    -- Pricing / terms
    h.terms,
    h.payment_method,
    h.cod_flag,
    h.gross_margin,
    h.order_disc_type,
    h.order_disc_factor,
    h.customer_disc_pct,
    h.freight_out_estimate,
    h.freight_charge_estimate,
    h.freight_tax,
    -- People
    h.taker,
    h.inside_sales,
    h.created_by,
    h.last_maintained_by,
    h.placed_by_name,
    h.engineer_id,
    -- Classification
    h.class_1id,
    h.class_2id,
    h.class_3id,
    h.class_4id,
    h.class_5id,
    h.source_id,
    h.source_code_no,
    h.source_location_id,
    h.job_name,
    h.import_source,
    -- Flags
    h.rma_flag,
    h.hold_invoice_flag,
    h.electronic_order_flag,
    h.delete_flag
FROM oe_hdr h
WHERE h.date_last_modified >= '2025-01-01'
  AND h.delete_flag = 'N'
ORDER BY h.date_last_modified DESC;


-- ── SO LINES ───────────────────────────────────────────────
SELECT
    l.order_no,
    l.oe_line_uid,
    l.oe_hdr_uid,
    l.line_no,
    l.user_line_no,
    l.line_seq_no,
    l.inv_mast_uid,
    l.detail_type,
    -- Item
    l.customer_part_number,
    l.extended_desc,
    l.additional_description,
    l.generic_custom_description,
    l.print_part_no,
    l.product_group_id,
    l.purchase_class_id,
    -- Quantities
    l.qty_ordered,
    l.original_qty_ordered,
    l.qty_allocated,
    l.original_qty_allocated,
    l.qty_on_pick_tickets,
    l.qty_invoiced,
    l.qty_staged,
    l.qty_canceled,
    l.qty_per_assembly,
    -- Pricing
    l.unit_price,
    l.original_unit_price,
    l.base_ut_price,
    l.extended_price,
    l.system_calc_unit_price,
    l.strategic_unit_price,
    l.retail_price,
    l.target_price,
    l.quoted_price,
    l.prediscount_unit_price,
    l.imported_price,
    l.manual_price_overide,
    l.calc_type,
    l.calc_value,
    l.line_discount,
    l.line_discount_description,
    l.cust_percentage_disc,
    l.ext_disc_amt,
    -- Costs
    l.sales_cost,
    l.commission_cost,
    l.other_cost,
    l.po_cost,
    l.ud_cost,
    l.freight_in,
    -- Units
    l.unit_of_measure,
    l.unit_size,
    l.unit_quantity,
    l.pricing_unit,
    l.pricing_unit_size,
    -- Dates
    l.required_date,
    l.expedite_date,
    l.pick_date,
    l.acknowledgement_date,
    l.awarded_date,
    l.date_created,
    l.date_last_modified,
    -- Source / disposition
    l.source_loc_id,
    l.ship_loc_id,
    l.supplier_id,
    l.disposition,
    l.original_disposition,
    l.item_source,
    l.carrier_id,
    -- Status
    l.complete,
    l.cancel_flag,
    l.delete_flag,
    l.scheduled,
    l.combinable,
    l.will_call,
    l.verified_flag,
    l.verified_code,
    l.routing_status_flag,
    l.split_flag,
    -- References
    l.cust_po_no,
    l.buyer,
    l.recipient,
    l.cost_center,
    l.gl_code,
    l.buyback_no,
    l.po_contract_number,
    l.reason_id,
    -- People
    l.created_by,
    l.last_maintained_by,
    -- Flags
    l.assembly,
    l.lot_bill,
    l.tax_item,
    l.other_charge,
    l.sample_flag,
    l.rental_flag,
    l.service_item_flag
FROM oe_line l
WHERE l.date_last_modified >= '2025-01-01'
  AND l.delete_flag = 'N'
ORDER BY l.order_no, l.line_no;
